### ISSUE TITLE
Issue installing into project

### ISSUE THREAD

**Issue by jamesbascle** [serilog/serilog-sinks-azureeventhub#10]
I have tried adding this to my project via NuGet.  My project targets .net framework 4.6.1.  I tried it when targeting 4.6.2 as well, but no dice.  Error message:

`Could not install package 'Serilog.Sinks.AzureEventHub 4.0.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
`

I guess in the most technical sense, I am doing what the error says to do, lol.

**Comment by nblumhardt** [comment]
Thanks for getting in touch :-) ... The .NET Standard docs suggest using the .NET Core 2.0 SDK - https://docs.microsoft.com/en-us/dotnet/standard/net-standard - is it possible you need a Visual Studio update? Cheers!

**Comment by jamesbascle** [comment]
Ahh quite possible.  I had an SDD failure about a month ago, it's quite possible I've not installed all the things I need to yet.  Thanks for the info.

**Comment by jamesbascle** [comment]
FYI, It basically looks like it's very finnicky to use 4.6.1 with .Net Standard on VS2015.  I moved to VS2017 and it worked like a charm.  Essentially 2015, even latest version "doesn't know 4.6.1 supports .net standard", or something like this.

**Comment by nblumhardt** [comment]
Thanks for the follow-up :+1:
