### ISSUE TITLE
Update to Azure.Messaging.EventHubs

### ISSUE THREAD

**Issue by alastairtree** [serilog/serilog-sinks-azureeventhub#22]
Seems like Microsoft.Azure.EventHubs has been replaced by Azure.Messaging.EventHubs. 

Creating this to track any work to migrate.

https://www.nuget.org/packages/Azure.Messaging.EventHubs/5.3.0

**Comment by mmckechney** [comment]
I have created PR #25 that resolves this issue.

**Comment by alastairtree** [comment]
That's a question for @nblumhardt

**Comment by nblumhardt** [comment]
Merged! I'm not up-to-date with event hubs (or this sink) so will need some feedback on the `-dev` package (should be published soon) before a "6.0" can be released.

Thanks for this, though!

**Comment by mmckechney** [comment]
Thanks @nblumhardt. The change is very straight forward. The Azure EventHub "Microsoft.Azure.EventHubs" SDK has been moved to maintenance support in favor of the newer version "Azure.Messaging.EventHubs". The code change updates the dependency and modifies some of the class names appropriately. There is no change to functionality.
